# Generated by Django 4.2.13 on 2024-06-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="The display label for the unit, eg: 'mL'")),
                ('unit_type', models.CharField(max_length=50, verbose_name='Type of measurement, eg: weight')),
            ],
            options={
                'verbose_name': 'Measure',
                'verbose_name_plural': 'Measures',
            },
        ),
        migrations.CreateModel(
            name='MeasureAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Alias name')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.measure')),
            ],
            options={
                'verbose_name': 'MeasureAlias',
                'verbose_name_plural': 'MeasureAliases',
            },
        ),
    ]
