# Generated by Django 4.2.13 on 2024-06-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurealias',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_aliases', to='measures.measure'),
        ),
    ]
