# Generated by Django 4.2.13 on 2024-06-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_user_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
