# Generated by Django 4.2.13 on 2024-06-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
