# Generated by Django 4.2.13 on 2024-06-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_alter_measurealias_measure'),
        ('recipes', '0004_alter_recipeingredient_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='measures.measure'),
        ),
    ]
