# Generated by Django 4.2.13 on 2024-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Recipe description/notes'),
        ),
    ]
