# Generated by Django 4.2.13 on 2024-09-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='version',
            field=models.IntegerField(blank=True, default=1, verbose_name='Recipe version number'),
        ),
    ]
